# Generated by Django 4.2.7 on 2023-12-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0003_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
