# Generated by Django 4.2.7 on 2023-12-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0006_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
