# Generated by Django 4.2.7 on 2023-12-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0011_commentlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='replies_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
