# Generated by Django 4.2.7 on 2023-12-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Youtube', '0013_alter_subscribers_channel_alter_subscribers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_img',
            field=models.ImageField(blank=True, upload_to='bg-images/'),
        ),
    ]
